### ISSUE TITLE
Broken Pipes

### ISSUE THREAD

**Issue by osiloke** [omeid/go-livereload#2]
Livereload spits out broken pipes(filesysem level) errors after a while, not sure right now what is closing connections to the filesystem

**Comment by omeid** [comment]
Can you share the errors please? 

Also, are you using he `cmd/livereload` or using the `liverelaod`?
If the second, please share the parts of code that is relevant.

**Comment by osiloke** [comment]
Sorry, but i haven't noticed this issue recently, and i'm not sure what exactly happened. I still need sometime to go back and properly debug the issue. It occured when i ran livereload (fresh install)

**Comment by omeid** [comment]
Hey, it has been a long time and haven't heard anything from you. So I am closing this issue, feel free to reopen it if you still have the problem.

Cheers.
